### ISSUE TITLE
Json parsing exception

### ISSUE THREAD

**Issue by mmiller678** [ipdata/dotnet#6]
```
var client = new IpDataClient(config.ApiKey);
IpInfo ipInfo = client.Lookup("185.153.176.5").Result;
```
Results in exception

Newtonsoft.Json.JsonReaderException
Unexpected character encountered while parsing value: {. Path 'asn', line 18, position 12.
   at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsString()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at IpData.IpDataClient.<Lookup>d__13.MoveNext()

**Comment by alexkhil** [comment]
Hi @mmiller678

I'm already working on new release of library where this issue will be fixed.

Thanks for your response.

**Comment by alexkhil** [comment]
Hi @mmiller678

Checkout [v2.0.0](https://github.com/alexkhil/IpData/releases/tag/v2.0.0)
Please, let me know if all works good for you.

Thanks.
